#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"

ENV_NAME="vla-adapter" \
CUDA_DEVICES="1,3" \
NPROC_PER_NODE="2" \
SKIP_CONVERT="1" \
DATASET_NAME="libero_suction_no_noops" \
RUN_ROOT_DIR="outputs" \
LEARNING_RATE="1e-4" \
LR_WARMUP_STEPS="500" \
SAVE_FREQ="500" \
BATCH_SIZE="2" \
GRAD_ACCUMULATION_STEPS="2" \
NUM_STEPS_BEFORE_DECAY="20000" \
MAX_STEPS="20005" \
CURR_ACTION_LOSS_WEIGHT="1.0" \
NEXT_ACTIONS_LOSS_WEIGHT="1.0" \
LOSS_TYPE="smooth_l1" \
FUTURE_HORIZON_WEIGHTS="1.0,1.2,1.5,2.0,2.5,3.0,3.0" \
TRANSITION_CHUNK_WEIGHT="4.0" \
TRANSITION_STEP_RADIUS="1" \
TRANSITION_DIM_WEIGHTS="1.25,1.25,2.5,1.0,1.0,1.0,4.0" \
TRANSITION_GRIPPER_THRESHOLD="0.5" \
TRANSITION_WEIGHT_WARMUP_STEPS="2000" \
ENABLE_CHECKPOINT_ROLLOUT_EVAL="False" \
CHECKPOINT_ROLLOUT_NUM_EPISODES="10" \
LAUNCH_METHOD="tmux" \
NUM_IMAGES_IN_INPUT="2" \
LORA_RANK="64" \
bash scripts/run_libero_suction_pipeline.sh
